ENEMY_SEED_STATS = {
    "enemy1": {"name_ja": "スクラップマイト", "image_path": "enemies/enemy1.png", "tier": 1, "element": "NORMAL", "hp": 28, "atk": 7, "def": 6, "spd": 8, "acc": 9, "cri": 2, "faction": "neutral"},
    "enemy2": {"name_ja": "スパークラット", "image_path": "enemies/enemy2.png", "tier": 1, "element": "THUNDER", "hp": 24, "atk": 8, "def": 5, "spd": 11, "acc": 12, "cri": 4, "faction": "neutral"},
    "enemy3": {"name_ja": "スクラップアイ", "image_path": "enemies/enemy3.png", "tier": 1, "element": "NORMAL", "hp": 26, "atk": 7, "def": 5, "spd": 7, "acc": 9, "cri": 2, "faction": "neutral"},
    "enemy4": {"name_ja": "アイアンポーン", "image_path": "enemies/enemy4.png", "tier": 2, "element": "STEEL", "hp": 42, "atk": 10, "def": 9, "spd": 8, "acc": 12, "cri": 3, "faction": "neutral"},
    "enemy5": {"name_ja": "ブレイズメック", "image_path": "enemies/enemy5.png", "tier": 2, "element": "FIRE", "hp": 40, "atk": 11, "def": 7, "spd": 10, "acc": 13, "cri": 5, "faction": "neutral"},
    "enemy6": {"name_ja": "エンバーレンチ", "image_path": "enemies/enemy6.png", "tier": 2, "element": "FIRE", "hp": 34, "atk": 10, "def": 6, "spd": 12, "acc": 14, "cri": 4, "faction": "neutral"},
    "enemy7": {"name_ja": "アクアスカウト", "image_path": "enemies/enemy7.png", "tier": 1, "element": "MACHINE", "hp": 30, "atk": 8, "def": 7, "spd": 9, "acc": 11, "cri": 3, "faction": "neutral"},
    "enemy8": {"name_ja": "ウィンドホッパー", "image_path": "enemies/enemy8.png", "tier": 2, "element": "WIND", "hp": 36, "atk": 9, "def": 7, "spd": 13, "acc": 14, "cri": 5, "faction": "neutral"},
    "enemy9": {"name_ja": "マグマソルジャー", "image_path": "enemies/enemy9.png", "tier": 2, "element": "FIRE", "hp": 46, "atk": 11, "def": 9, "spd": 9, "acc": 12, "cri": 4, "faction": "neutral", "trait": "berserk"},
    "enemy10": {"name_ja": "マグマガード", "image_path": "enemies/enemy10.png", "tier": 3, "element": "FIRE", "hp": 57, "atk": 13, "def": 11, "spd": 8, "acc": 13, "cri": 4, "faction": "neutral", "trait": "berserk"},
    "enemy11": {"name_ja": "フロストガード", "image_path": "enemies/enemy11.png", "tier": 3, "element": "ICE", "hp": 54, "atk": 12, "def": 11, "spd": 9, "acc": 14, "cri": 4, "faction": "neutral"},
    "enemy12": {"name_ja": "ウィンドスプライト", "image_path": "enemies/enemy12.png", "tier": 2, "element": "WIND", "hp": 32, "atk": 9, "def": 6, "spd": 14, "acc": 15, "cri": 4, "faction": "neutral", "trait": "fast"},
    "enemy13": {"name_ja": "ボルトブレード", "image_path": "enemies/enemy13.png", "tier": 3, "element": "THUNDER", "hp": 49, "atk": 13, "def": 9, "spd": 13, "acc": 15, "cri": 6, "faction": "neutral"},
    "enemy14": {"name_ja": "スチールスカウト", "image_path": "enemies/enemy14.png", "tier": 2, "element": "STEEL", "hp": 42, "atk": 10, "def": 9, "spd": 10, "acc": 13, "cri": 3, "faction": "aurix", "trait": "heavy"},
    "enemy15": {"name_ja": "フレイムブレード", "image_path": "enemies/enemy15.png", "tier": 3, "element": "FIRE", "hp": 47, "atk": 14, "def": 8, "spd": 12, "acc": 14, "cri": 6, "faction": "neutral"},
    "enemy16": {"name_ja": "アイアンブルワーク", "image_path": "enemies/enemy16.png", "tier": 3, "element": "STEEL", "hp": 58, "atk": 12, "def": 12, "spd": 7, "acc": 12, "cri": 3, "faction": "neutral", "trait": "heavy"},
    "enemy17": {"name_ja": "オアベヒモス", "image_path": "enemies/enemy17.png", "tier": 3, "element": "ORE", "hp": 58, "atk": 13, "def": 12, "spd": 7, "acc": 13, "cri": 3, "faction": "neutral", "trait": "heavy"},
    "enemy18": {"name_ja": "アメジストブルワーク", "image_path": "enemies/enemy18.png", "tier": 3, "element": "ORE", "hp": 58, "atk": 12, "def": 12, "spd": 7, "acc": 12, "cri": 4, "faction": "neutral"},
    "enemy19": {"name_ja": "ドリルボット", "image_path": "enemies/enemy19.png", "tier": 1, "element": "MACHINE", "hp": 30, "atk": 9, "def": 6, "spd": 9, "acc": 11, "cri": 3, "faction": "neutral"},
    "enemy20": {"name_ja": "ストーンアイ", "image_path": "enemies/enemy20.png", "tier": 1, "element": "ORE", "hp": 34, "atk": 8, "def": 9, "spd": 6, "acc": 10, "cri": 2, "faction": "neutral"},
    "enemy21": {"name_ja": "ジャンクスパーク", "image_path": "enemies/enemy21.png", "tier": 1, "element": "MACHINE", "hp": 26, "atk": 7, "def": 5, "spd": 10, "acc": 12, "cri": 4, "faction": "neutral"},
    "enemy22": {"name_ja": "テスラポッド", "image_path": "enemies/enemy22.png", "tier": 2, "element": "THUNDER", "hp": 34, "atk": 10, "def": 7, "spd": 11, "acc": 14, "cri": 5, "faction": "neutral"},
    "enemy23": {"name_ja": "ウィンドコプター", "image_path": "enemies/enemy23.png", "tier": 2, "element": "WIND", "hp": 30, "atk": 9, "def": 6, "spd": 15, "acc": 15, "cri": 4, "faction": "neutral", "trait": "fast"},
    "enemy24": {"name_ja": "フロストブロブ", "image_path": "enemies/enemy24.png", "tier": 1, "element": "ICE", "hp": 32, "atk": 8, "def": 7, "spd": 8, "acc": 10, "cri": 2, "faction": "neutral"},
    "enemy25": {"name_ja": "ラヴァコア", "image_path": "enemies/enemy25.png", "tier": 3, "element": "FIRE", "hp": 57, "atk": 14, "def": 10, "spd": 9, "acc": 13, "cri": 5, "faction": "neutral", "trait": "unstable"},
    "enemy26": {"name_ja": "ラヴァミニ", "image_path": "enemies/enemy26.png", "tier": 2, "element": "FIRE", "hp": 40, "atk": 11, "def": 7, "spd": 11, "acc": 13, "cri": 4, "faction": "neutral"},
    "enemy27": {"name_ja": "スクラップスパイダー", "image_path": "enemies/enemy27.png", "tier": 1, "element": "NORMAL", "hp": 26, "atk": 8, "def": 5, "spd": 12, "acc": 12, "cri": 3, "faction": "neutral"},
    "enemy28": {"name_ja": "アイスドローン", "image_path": "enemies/enemy28.png", "tier": 2, "element": "ICE", "hp": 36, "atk": 10, "def": 7, "spd": 12, "acc": 14, "cri": 4, "faction": "neutral"},
    "enemy29": {"name_ja": "アイスガーディアン", "image_path": "enemies/enemy29.png", "tier": 3, "element": "ICE", "hp": 51, "atk": 12, "def": 10, "spd": 11, "acc": 14, "cri": 4, "faction": "neutral", "trait": "heavy"},
    "enemy30": {"name_ja": "アイスコア", "image_path": "enemies/enemy30.png", "tier": 3, "element": "ICE", "hp": 58, "atk": 13, "def": 11, "spd": 10, "acc": 14, "cri": 4, "faction": "neutral"},
    "fort_ironbulk": {"name_ja": "重装機アイアンバルク", "image_path": "enemies/layer4/fort_ironbulk.png", "tier": 4, "element": "STEEL", "hp": 190, "atk": 42, "def": 58, "spd": 18, "acc": 34, "cri": 8, "faction": "aurix", "trait": "heavy"},
    "fort_platehound": {"name_ja": "装甲獣プレートハウンド", "image_path": "enemies/layer4/fort_platehound.png", "tier": 4, "element": "ORE", "hp": 174, "atk": 48, "def": 50, "spd": 20, "acc": 36, "cri": 10, "faction": "aurix", "trait": "heavy"},
    "fort_bastion_eye": {"name_ja": "要塞眼バスティオンアイ", "image_path": "enemies/layer4/fort_bastion_eye.png", "tier": 4, "element": "STEEL", "hp": 166, "atk": 38, "def": 60, "spd": 22, "acc": 38, "cri": 6, "faction": "aurix", "trait": "heavy"},
    "haze_mirage_mite": {"name_ja": "幻霧機ミラージュマイト", "image_path": "enemies/layer4/haze_mirage_mite.png", "tier": 4, "element": "WIND", "hp": 142, "atk": 38, "def": 34, "spd": 56, "acc": 42, "cri": 12, "faction": "ventra", "trait": "fast"},
    "haze_fog_lancer": {"name_ja": "霧槍機フォグランサー", "image_path": "enemies/layer4/haze_fog_lancer.png", "tier": 4, "element": "WIND", "hp": 134, "atk": 44, "def": 30, "spd": 60, "acc": 44, "cri": 12, "faction": "ventra", "trait": "fast"},
    "haze_glint_drone": {"name_ja": "閃霧機グリントドローン", "image_path": "enemies/layer4/haze_glint_drone.png", "tier": 4, "element": "MACHINE", "hp": 126, "atk": 34, "def": 28, "spd": 64, "acc": 48, "cri": 10, "faction": "ventra", "trait": "fast"},
    "burst_coreling": {"name_ja": "暴核機コアリング", "image_path": "enemies/layer4/burst_coreling.png", "tier": 4, "element": "FIRE", "hp": 126, "atk": 52, "def": 22, "spd": 42, "acc": 34, "cri": 18, "faction": "ignis", "trait": "unstable"},
    "burst_shockfang": {"name_ja": "雷牙機ショックファング", "image_path": "enemies/layer4/burst_shockfang.png", "tier": 4, "element": "THUNDER", "hp": 130, "atk": 58, "def": 26, "spd": 38, "acc": 36, "cri": 20, "faction": "ignis", "trait": "berserk"},
    "burst_ruptgear": {"name_ja": "破動機ラプトギア", "image_path": "enemies/layer4/burst_ruptgear.png", "tier": 4, "element": "FIRE", "hp": 144, "atk": 64, "def": 28, "spd": 34, "acc": 38, "cri": 22, "faction": "ignis", "trait": "berserk"},
    "boss_aurix_guardian": {"name_ja": "オリクス・ガーディアン", "image_path": "enemies/boss/boss_aurix_guardian.png", "tier": 1, "element": "STEEL", "hp": 88, "atk": 10, "def": 12, "spd": 11, "acc": 12, "cri": 4, "faction": "aurix", "is_boss": 1, "boss_area_key": "layer_1", "trait": "heavy"},
    "boss_ventra_sentinel": {"name_ja": "ヴェントラ・センチネル", "image_path": "enemies/boss/boss_ventra_sentinel.png", "tier": 2, "element": "WIND", "hp": 97, "atk": 13, "def": 10, "spd": 15, "acc": 20, "cri": 5, "faction": "ventra", "is_boss": 1, "boss_area_key": "layer_2", "trait": "fast"},
    "boss_ignis_reaver": {"name_ja": "イグニス・リーヴァー", "image_path": "enemies/boss/boss_ignis_reaver.png", "tier": 3, "element": "FIRE", "hp": 122, "atk": 19, "def": 13, "spd": 13, "acc": 14, "cri": 8, "faction": "ignis", "is_boss": 1, "boss_area_key": "layer_3", "trait": "berserk"},
    "boss_4_forge_elguard": {"name_ja": "要塞機エルガード", "image_path": "enemies/boss/boss_4_forge_elguard.png", "tier": 4, "element": "STEEL", "hp": 360, "atk": 64, "def": 86, "spd": 20, "acc": 38, "cri": 8, "faction": "aurix", "is_boss": 1, "boss_area_key": "layer_4_forge", "trait": "heavy"},
    "boss_4_haze_mirage": {"name_ja": "霧界機ミラージュ", "image_path": "enemies/boss/boss_4_haze_mirage.png", "tier": 4, "element": "WIND", "hp": 278, "atk": 66, "def": 48, "spd": 78, "acc": 52, "cri": 14, "faction": "ventra", "is_boss": 1, "boss_area_key": "layer_4_haze", "trait": "fast"},
    "boss_4_burst_volterio": {"name_ja": "暴核機ヴォルテリオ", "image_path": "enemies/boss/boss_4_burst_volterio.png", "tier": 4, "element": "FIRE", "hp": 268, "atk": 86, "def": 38, "spd": 38, "acc": 42, "cri": 26, "faction": "ignis", "is_boss": 1, "boss_area_key": "layer_4_burst", "trait": "berserk"},
    "boss_4_final_ark_zero": {"name_ja": "機巧審判アーク=ゼロ", "image_path": "enemies/boss/boss_4_final_ark_zero.png", "tier": 4, "element": "MACHINE", "hp": 398, "atk": 80, "def": 68, "spd": 46, "acc": 46, "cri": 16, "faction": "neutral", "is_boss": 1, "boss_area_key": "layer_4_final", "trait": "heavy"},
    "lab_guardian_veil": {"name_ja": "観測機ヴェイルガーディアン", "image_path": "enemies/layer5/lab_guardian_veil.png", "tier": 5, "element": "WIND", "hp": 182, "atk": 58, "def": 46, "spd": 68, "acc": 52, "cri": 10, "faction": "ventra", "trait": "fast"},
    "lab_bulwark_node": {"name_ja": "防壁核ノードバルク", "image_path": "enemies/layer5/lab_bulwark_node.png", "tier": 5, "element": "STEEL", "hp": 228, "atk": 54, "def": 70, "spd": 22, "acc": 46, "cri": 6, "faction": "aurix", "trait": "heavy"},
    "lab_trace_hound": {"name_ja": "追跡獣トレースハウンド", "image_path": "enemies/layer5/lab_trace_hound.png", "tier": 5, "element": "MACHINE", "hp": 166, "atk": 62, "def": 38, "spd": 72, "acc": 54, "cri": 12, "faction": "ventra", "trait": "fast"},
    "lab_fault_keeper": {"name_ja": "保守機フォルトキーパー", "image_path": "enemies/layer5/lab_fault_keeper.png", "tier": 5, "element": "STEEL", "hp": 198, "atk": 56, "def": 62, "spd": 28, "acc": 48, "cri": 8, "faction": "aurix", "trait": "heavy"},
    "pin_flare_beast": {"name_ja": "閃核獣フレアビースト", "image_path": "enemies/layer5/pin_flare_beast.png", "tier": 5, "element": "FIRE", "hp": 152, "atk": 74, "def": 30, "spd": 42, "acc": 46, "cri": 20, "faction": "ignis", "trait": "berserk"},
    "pin_rupture_eye": {"name_ja": "裂光眼ラプチャーアイ", "image_path": "enemies/layer5/pin_rupture_eye.png", "tier": 5, "element": "THUNDER", "hp": 136, "atk": 70, "def": 26, "spd": 50, "acc": 48, "cri": 22, "faction": "ignis", "trait": "unstable"},
    "pin_scorch_fang": {"name_ja": "焦牙機スコーチファング", "image_path": "enemies/layer5/pin_scorch_fang.png", "tier": 5, "element": "FIRE", "hp": 144, "atk": 80, "def": 28, "spd": 46, "acc": 44, "cri": 24, "faction": "ignis", "trait": "berserk"},
    "pin_crash_gear": {"name_ja": "衝核機クラッシュギア", "image_path": "enemies/layer5/pin_crash_gear.png", "tier": 5, "element": "ORE", "hp": 160, "atk": 84, "def": 32, "spd": 38, "acc": 46, "cri": 26, "faction": "ignis", "trait": "unstable"},
    "boss_5_labyrinth_nyx_array": {"name_ja": "観測群体ニクスアレイ", "image_path": "enemies/boss/boss_5_labyrinth_nyx_array.png", "tier": 5, "element": "WIND", "hp": 374, "atk": 76, "def": 62, "spd": 84, "acc": 58, "cri": 12, "faction": "ventra", "is_boss": 1, "boss_area_key": "layer_5_labyrinth", "trait": "fast"},
    "boss_5_pinnacle_ignition_king": {"name_ja": "覇走機イグニッションキング", "image_path": "enemies/boss/boss_5_pinnacle_ignition_king.png", "tier": 5, "element": "FIRE", "hp": 344, "atk": 102, "def": 36, "spd": 50, "acc": 48, "cri": 30, "faction": "ignis", "is_boss": 1, "boss_area_key": "layer_5_pinnacle", "trait": "berserk"},
    "boss_5_final_omega_frame": {"name_ja": "終機オメガフレーム", "image_path": "enemies/boss/boss_5_final_omega_frame.png", "tier": 5, "element": "MACHINE", "hp": 460, "atk": 94, "def": 74, "spd": 58, "acc": 52, "cri": 20, "faction": "neutral", "is_boss": 1, "boss_area_key": "layer_5_final", "trait": "heavy"},
}

COIN_REWARD_BY_TIER = {
    1: 2,
    2: 3,
    3: 4,
    4: 5,
    5: 6,
}

DROP_TYPE_WEIGHTS_BY_TIER = {
    1: {"coin_only": 60, "parts_1": 38, "parts_2": 2},
    2: {"coin_only": 50, "parts_1": 45, "parts_2": 5},
    3: {"coin_only": 40, "parts_1": 55, "parts_2": 5},
    4: {"coin_only": 35, "parts_1": 53, "parts_2": 12},
    5: {"coin_only": 30, "parts_1": 50, "parts_2": 20},
}

RARITY_WEIGHTS_BY_TIER = {
    1: {"N": 78, "R": 20, "SR": 2, "SSR": 0, "UR": 0},
    2: {"N": 55, "R": 35, "SR": 9, "SSR": 1, "UR": 0},
    3: {"N": 35, "R": 40, "SR": 20, "SSR": 4, "UR": 1},
    4: {"N": 25, "R": 38, "SR": 26, "SSR": 8, "UR": 3},
    5: {"N": 18, "R": 34, "SR": 28, "SSR": 14, "UR": 6},
}

PLUS_WEIGHTS_BY_TIER = {
    1: {0: 100},
    2: {0: 95, 1: 5},
    3: {0: 88, 1: 10, 2: 2},
    4: {0: 80, 1: 15, 2: 5},
    5: {0: 68, 1: 20, 2: 9, 3: 3},
}

FUSE_COST_BY_PLUS = {
    0: 1,
    1: 2,
    2: 3,
    3: 4,
    4: 6,
    5: 8,
    6: 10,
    7: 12,
    8: 15,
    9: 20,
}
