import os

RARITIES = ("N", "R", "SR", "SSR", "UR")
APP_VERSION = "0.1.54"
SUPPORT_EMAIL = os.getenv("SUPPORT_EMAIL", "pochirobo021@gmail.com").strip() or "pochirobo021@gmail.com"
LEGAL_OPERATOR_NAME = os.getenv("LEGAL_OPERATOR_NAME", "大谷周平").strip() or "大谷周平"
LEGAL_BRAND_NAME = os.getenv("LEGAL_BRAND_NAME", "KAS Development").strip() or "KAS Development"
LEGAL_DISCLOSURE_POLICY = (
    os.getenv("LEGAL_DISCLOSURE_POLICY", "所在地・電話番号は請求があった場合、遅滞なく開示いたします。").strip()
    or "所在地・電話番号は請求があった場合、遅滞なく開示いたします。"
)

ELEMENTS = (
    ("NORMAL", "無"),
    ("FIRE", "炎"),
    ("WATER", "水"),
    ("THUNDER", "雷"),
    ("WIND", "風"),
    ("ICE", "氷"),
    ("STEEL", "鋼"),
    ("MACHINE", "機械"),
    ("ORE", "鉱石"),
)

ELEMENT_LABEL_MAP = {code: label for code, label in ELEMENTS}

SET_BONUS_TABLE = {
    "NORMAL": ("hp", 0.05),
    "FIRE": ("atk", 0.05),
    "WATER": ("spd", 0.05),
    "THUNDER": ("cri", 0.05),
    "WIND": ("acc", 0.05),
    "ICE": ("def", 0.05),
    "STEEL": ("def", 0.05),
    "MACHINE": ("acc", 0.05),
    "ORE": ("cri", 0.05),
}

# plus -> (success_rate, great_success_rate)
# great success rate is evaluated only inside success window.
FUSE_SUCCESS_TABLE = {
    0: (90, 15),
    1: (80, 15),
    2: (70, 14),
    3: (60, 13),
    4: (50, 12),
    5: (40, 11),
    6: (30, 10),
    7: (20, 10),
    8: (12, 9),
    9: (7, 8),
}

PLUS_WEIGHT_BONUS_K = 6
PLUS_WEIGHT_BONUS_CAP_MULTIPLIER = 2

FACTION_LABELS = {
    "aurix": "オリクス",
    "ventra": "ヴェントラ",
    "ignis": "イグニス",
    "neutral": "旧文明",
}

FACTION_ICONS = {
    "aurix": None,
    "ventra": None,
    "ignis": None,
    "neutral": None,
}

FACTION_EMBLEMS = {
    "aurix": "images/factions/aurix.png",
    "ignis": "images/factions/ignis.png",
    "ventra": "images/factions/ventra.png",
}

ENCOUNTER_LOGS = {
    "aurix": {
        1: [
            "巡回中のオリクス機《{enemy_name}》が現れた。",
            "管理区域でオリクス機《{enemy_name}》と遭遇。",
        ],
        2: [
            "装甲を強化したオリクス機《{enemy_name}》が立ちはだかる。",
            "防衛プロトコル発動。オリクス機《{enemy_name}》が迎撃。",
        ],
        3: [
            "重装オリクス機《{enemy_name}》が起動。",
            "深層防衛機《{enemy_name}》…反応が強い。",
        ],
    },
    "ventra": {
        1: [
            "高速機《{enemy_name}》が接近。ヴェントラ所属だ。",
            "ヴェントラ機《{enemy_name}》が旋回している。",
        ],
        2: [
            "加速反応。ヴェントラ機《{enemy_name}》が突入。",
            "機動強化型《{enemy_name}》がロックオン。",
        ],
        3: [
            "強襲型ヴェントラ機《{enemy_name}》が現れた。",
            "索敵妨害を確認。《{enemy_name}》の動きが読めない。",
        ],
    },
    "ignis": {
        1: [
            "試験機《{enemy_name}》が起動。イグニス製だ。",
            "コアが光る。《{enemy_name}》が動き出した。",
        ],
        2: [
            "出力上昇。イグニス機《{enemy_name}》が暴れ出す。",
            "不安定な機体《{enemy_name}》が迫る。",
        ],
        3: [
            "高出力コア機《{enemy_name}》が覚醒。",
            "制御不能。《{enemy_name}》が突進してくる。",
        ],
    },
    "neutral": {
        1: [
            "所属不明機《{enemy_name}》が現れた。",
            "古い機体《{enemy_name}》が起動する。",
        ],
        2: [
            "旧文明機《{enemy_name}》が静かに構える。",
            "解析不能。《{enemy_name}》の反応が強い。",
        ],
        3: [
            "深層機《{enemy_name}》が目を覚ました。",
            "規格外のコア反応。《{enemy_name}》が覚醒。",
        ],
    },
}

MID_LOGS_COMMON = [
    "火花が散る。",
    "装甲がきしむ。",
    "駆動音が跳ねる。",
    "視界が揺れる。",
    "照準がぶれる。",
]

MID_LOGS_FACTION = {
    "aurix": ["防衛プロトコルが更新された。", "装甲板が閉じる。"],
    "ventra": ["加速音が近づく。", "軌道が読めない。"],
    "ignis": ["熱が上がる。", "不規則な振動…。"],
    "neutral": ["ノイズが増える。", "静かに圧が増す。"],
}

VICTORY_LOGS = [
    "戦闘終了。回収成功。",
    "停止を確認。パーツを回収した。",
]

DEFEAT_LOGS = [
    "撤退。次に備えよう。",
    "損傷が大きい。帰還する。",
]

AUDIT_EVENT_TYPES = {
    "HOME_VIEW": "audit.home.view",
    "HOME_NEXT_ACTION_VIEW": "audit.home.next_action.view",
    "HOME_NEXT_ACTION_CLICK": "audit.home.next_action.click",
    "HOME_QUICK_START": "audit.home.quick_start",
    "HOME_PREVIOUS_AREA_CLICK": "audit.home.previous_area.click",
    "EXPLORE_START": "audit.explore.start",
    "EXPLORE_END": "audit.explore.end",
    "EXPLORE_FAILED": "audit.explore.failed",
    "COIN_DELTA": "audit.coin.delta",
    "STREAK_BONUS": "audit.streak.bonus",
    "DROP": "audit.drop",
    "MODULE_DROP": "audit.module.drop",
    "MODULE_SELECT": "audit.module.select",
    "MODULE_LOADOUT_SET": "audit.module.loadout.set",
    "MODULE_LOADOUT_CLEAR": "audit.module.loadout.clear",
    "MODULE_SYNERGY_APPLY": "audit.module.synergy.apply",
    "MODULE_CONSUME": "audit.module.consume",
    "MODULE_PROTOCOL_SET": "audit.module.protocol.set",
    "MODULE_PROTOCOL_CLEAR": "audit.module.protocol.clear",
    "MODULE_PROTOCOL_AUTO_CLEAR": "audit.module.protocol.auto_clear",
    "MODULE_PROTOCOL_START": "audit.module.protocol.start",
    "MODULE_PROTOCOL_TRIGGER": "audit.module.protocol.trigger",
    "MODULE_PROTOCOL_FINISH": "audit.module.protocol.finish",
    "MODULE_BATTLE_CODE_SET": "audit.module.battle_code.set",
    "MODULE_BATTLE_CODE_CLEAR": "audit.module.battle_code.clear",
    "MODULE_BATTLE_CODE_START": "audit.module.battle_code.start",
    "MODULE_BATTLE_CODE_CONDITION": "audit.module.battle_code.condition",
    "MODULE_BATTLE_CODE_TRIGGER": "audit.module.battle_code.trigger",
    "MODULE_BATTLE_CODE_CONSUME": "audit.module.battle_code.consume",
    "MODULE_BATTLE_CODE_FINISH": "audit.module.battle_code.finish",
    "MODULE_BATTLE_CODE_LIBRARY_CREATE": "audit.module.battle_code.library.create",
    "MODULE_BATTLE_CODE_LIBRARY_OVERWRITE": "audit.module.battle_code.library.overwrite",
    "MODULE_BATTLE_CODE_LIBRARY_DELETE": "audit.module.battle_code.library.delete",
    "MODULE_BATTLE_CODE_LIBRARY_SELECT": "audit.module.battle_code.library.select",
    "MODULE_BATTLE_CODE_LIBRARY_UNSELECT": "audit.module.battle_code.library.unselect",
    "MODULE_BATTLE_CODE_LIBRARY_LABEL_UPDATE": "audit.module.battle_code.library.label_update",
    "MODULE_BATTLE_CODE_LIBRARY_SHARE": "audit.module.battle_code.library.share",
    "MODULE_BATTLE_CODE_LIBRARY_MIGRATE": "audit.module.battle_code.library.migrate",
    "MODULE_BATTLE_CODE_LIBRARY_FALLBACK": "audit.module.battle_code.library.fallback",
    "MODULE_BATTLE_CODE_LIBRARY_STATS_UPDATE": "audit.module.battle_code.library.stats_update",
    "ROBOT_TUNING_XP_GAIN": "audit.robot.tuning.xp_gain",
    "ROBOT_TUNING_DAILY_CAP": "audit.robot.tuning.daily_cap",
    "ROBOT_TUNING_RESET": "audit.robot.tuning.reset",
    "ROBOT_TUNING_ALLOCATE": "audit.robot.tuning.allocate",
    "ROBOT_TUNING_COMPLETE": "audit.robot.tuning.complete",
    "RESEARCH_TASK_ASSIGN": "audit.research.task.assign",
    "RESEARCH_TASK_PROGRESS": "audit.research.task.progress",
    "RESEARCH_TASK_COMPLETE": "audit.research.task.complete",
    "RESEARCH_TASK_CLAIM": "audit.research.task.claim",
    "RESEARCH_TASK_HOLD": "audit.research.task.hold",
    "RESEARCH_LEVEL_UP": "audit.research.level.up",
    "RESEARCH_DISCOVERY": "audit.research.discovery",
    "PERSONAL_RECORD_UPDATE": "audit.personal_record.update",
    "RESEARCH_TRIAL_START": "audit.research.trial.start",
    "RESEARCH_TRIAL_COMPLETE": "audit.research.trial.complete",
    "RESEARCH_ANALYSIS_START": "audit.research.analysis.start",
    "RESEARCH_ANALYSIS_COMPLETE": "audit.research.analysis.complete",
    "MODULE_PITY_PROGRESS": "audit.module.pity.progress",
    "MODULE_PITY_GRANT": "audit.module.pity.grant",
    "MODULE_COMBINE": "audit.module.combine",
    "MODULE_CATALOG_REGISTER": "audit.module.catalog.register",
    "MODULE_LOCK": "audit.module.lock",
    "MODULE_UNLOCK": "audit.module.unlock",
    "MODULE_SELL": "audit.module.sell",
    "MODULE_SYNTHESIS_PREVIEW": "audit.module.synthesis.preview",
    "MODULE_SYNTHESIS_CREATE": "audit.module.synthesis.create",
    "MODULE_SYNTHESIS_CONSUME": "audit.module.synthesis.consume",
    "MODULE_SYNTHESIS_RESULT": "audit.module.synthesis.result",
    "MODULE_STRATEGY_APPLY": "audit.module.strategy.apply",
    "MODULE_STRATEGY_RESULT": "audit.module.strategy.result",
    "MODULE_TRAIT_TRIGGER": "audit.module.trait.trigger",
    "MODULE_REROLL": "audit.module.reroll",
    "MODULE_REROLL_CANDIDATE_CREATE": "audit.module.reroll.candidate.create",
    "MODULE_REROLL_ACCEPT": "audit.module.reroll.accept",
    "MODULE_REROLL_REJECT": "audit.module.reroll.reject",
    "MODULE_REROLL_EXPIRE": "audit.module.reroll.expire",
    "MODULE_REROLL_RESTORE": "audit.module.reroll.restore",
    "FACTORY_ENSURE_DEFAULTS": "audit.factory.ensure_defaults",
    "FACTORY_CLAIM": "audit.factory.claim",
    "FACTORY_UPGRADE": "audit.factory.upgrade",
    "FACTORY_PRIZE_ENSURE_DEFAULTS": "audit.factory.prize.ensure_defaults",
    "FACTORY_PRIZE_CLAIM": "audit.factory.prize.claim",
    "FACTORY_RESEARCH_ENSURE_DEFAULTS": "audit.factory.research.ensure_defaults",
    "FACTORY_RESEARCH_DONATE": "audit.factory.research.donate",
    "FACTORY_RESEARCH_COMPLETE": "audit.factory.research.complete",
    "FACTORY_COSMETIC_ENSURE_DEFAULTS": "audit.factory.cosmetic.ensure_defaults",
    "FACTORY_COSMETIC_UNLOCK": "audit.factory.cosmetic.unlock",
    "FACTORY_COSMETIC_EQUIP": "audit.factory.cosmetic.equip",
    "FACTORY_POINTS_DELTA": "audit.factory.points.delta",
    "COMPANION_ENSURE_DEFAULTS": "audit.companion.ensure_defaults",
    "COMPANION_UNLOCK": "audit.companion.unlock",
    "COMPANION_EQUIP": "audit.companion.equip",
    "COMPANION_UPGRADE": "audit.companion.upgrade",
    "COMPANION_DISPATCH_ENSURE_DEFAULTS": "audit.companion.dispatch.ensure_defaults",
    "COMPANION_DISPATCH_START": "audit.companion.dispatch.start",
    "COMPANION_DISPATCH_CLAIM": "audit.companion.dispatch.claim",
    "COMPANION_DISPATCH_EVENT": "audit.companion.dispatch.event",
    "COMPANION_DISPATCH_MATERIAL_REWARD": "audit.companion.dispatch.material.reward",
    "COMPANION_ALBUM_PHOTO_ENSURE_DEFAULTS": "audit.companion.album.photo.ensure_defaults",
    "COMPANION_ALBUM_PHOTO_UNLOCK": "audit.companion.album.photo.unlock",
    "MATERIAL_ENSURE_DEFAULTS": "audit.material.ensure_defaults",
    "MATERIAL_DELTA": "audit.material.delta",
    "BASE_VIEW": "audit.base.view",
    "BASE_LIKE": "audit.base.like",
    "BASE_RANKING_VIEW": "audit.base.ranking.view",
    "INVENTORY_DELTA": "audit.inventory.delta",
    "PART_AUTO_SELL": "audit.part.auto_sell",
    "PART_OVERFLOW_CLEANUP_SELL": "audit.part.overflow_cleanup_sell",
    "PART_INVENTORY_EXPAND": "audit.part_inventory.expand",
    "PART_LOCK": "audit.part.lock",
    "PART_UNLOCK": "audit.part.unlock",
    "FUSE": "audit.fuse",
    "FUSE_BATCH_PREVIEW": "audit.fuse.batch_preview",
    "FUSE_BATCH_EXECUTE": "audit.fuse.batch_execute",
    "BUILD_CONFIRM": "audit.build.confirm",
    "DAILY_RESEARCH_VIEW": "audit.daily_research.view",
    "DAILY_RESEARCH_PROGRESS": "audit.daily_research.progress",
    "DAILY_RESEARCH_COMPLETE": "audit.daily_research.complete",
    "DAILY_RESEARCH_REWARD": "audit.daily_research.reward",
    "ROBOT_DECOMPOSE": "audit.robot.decompose",
    "ROBOT_DECOMPOSE_BLOCKED": "audit.robot.decompose.blocked",
    "ROBOT_RENAME": "audit.robot.rename",
    "ROBOT_MAINTENANCE": "audit.robot.maintenance",
    "ROBOT_CUSTOMIZE_CTA_CLICK": "audit.robot.customize.cta_click",
    "ROBOT_CONTEST_VIEW": "audit.robot.contest.view",
    "ROBOT_CONTEST_SUBMIT": "audit.robot.contest.submit",
    "CHAMPION_SELECT": "audit.champion.select",
    "CHAMPION_CHALLENGE": "audit.champion.challenge",
    "CHAMPION_DEFEAT": "audit.champion.defeat",
    "SHOWCASE_EXPAND": "audit.showcase.expand",
    "SHOWCASE_LIKE": "audit.showcase.like",
    "SHOWCASE_BATTLE": "audit.showcase.battle",
    "ROBOT_SHARE": "audit.robot.share",
    "CHAT_POST": "audit.chat.post",
    "BOSS_ENCOUNTER": "audit.boss.encounter",
    "BOSS_ATTEMPT": "audit.boss.attempt",
    "BOSS_DEFEAT": "audit.boss.defeat",
    "BOSS_RETRY_RESULT": "audit.boss.retry.result",
    "BOSS_RETRY_CTA_VIEW": "audit.boss.retry.cta.view",
    "BOSS_RETRY_CTA_CLICK": "audit.boss.retry.cta.click",
    "BOSS_RETRY_PARTS_CLICK": "audit.boss.retry.parts_click",
    "LAYER_UNLOCK": "audit.layer.unlock",
    "LAYER_UNLOCK_INCONSISTENT": "audit.layer.unlock.inconsistent",
    "LAYER2_UNLOCK_CTA_VIEW": "audit.layer2.unlock_cta.view",
    "LAYER2_UNLOCK_CTA_CLICK": "audit.layer2.unlock_cta.click",
    "FACTION_FACILITY_ENSURE": "audit.faction.facility.ensure",
    "FACTION_FACILITY_RECALCULATE": "audit.faction.facility.recalculate",
    "FACTION_FACILITY_GRANT": "audit.faction.facility.grant",
    "FACTION_TERRITORY_ENSURE": "audit.faction.territory.ensure",
    "FACTION_TERRITORY_RECALCULATE": "audit.faction.territory.recalculate",
    "FACTION_TERRITORY_FINALIZE": "audit.faction.territory.finalize",
    "FACTION_TITLES_GRANT_WEEKLY": "audit.faction.titles.grant_weekly",
    "FACTION_TITLES_GRANT_MANUAL": "audit.faction.titles.grant_manual",
    "FACTION_WEEKLY_EVENT_SET": "audit.faction.weekly_event.set",
    "FACTION_WEEKLY_EVENT_ACTIVATE": "audit.faction.weekly_event.activate",
    "FACTION_WEEKLY_EVENT_FINALIZE": "audit.faction.weekly_event.finalize",
    "FACTION_WEEKLY_EVENT_CANCEL": "audit.faction.weekly_event.cancel",
    "FACTION_SHOP_ENSURE_DEFAULTS": "audit.faction.shop.ensure_defaults",
    "FACTION_SHOP_CREATE": "audit.faction.shop.create",
    "FACTION_SHOP_UPDATE": "audit.faction.shop.update",
    "FACTION_SHOP_PURCHASE": "audit.faction.shop.purchase",
    "FACTION_SHOP_EQUIP": "audit.faction.shop.equip",
    "FACTION_QUEST_GENERATE": "audit.faction.quest.generate",
    "FACTION_QUEST_PROGRESS": "audit.faction.quest.progress",
    "FACTION_QUEST_COMPLETE": "audit.faction.quest.complete",
    "FACTION_QUEST_REWARD_CLAIM": "audit.faction.quest.reward_claim",
    "FACTION_QUEST_FINALIZE": "audit.faction.quest.finalize",
    "FACTION_QUEST_CANCEL": "audit.faction.quest.cancel",
    "TOWER_RUN_START": "audit.tower.run.start",
    "TOWER_BATTLE": "audit.tower.battle",
    "TOWER_RUN_COMPLETE": "audit.tower.run.complete",
    "ACHIEVEMENT_GRANT": "audit.achievement.grant",
    "ACHIEVEMENT_EQUIP": "audit.achievement.equip",
    "TOWER_RUN_FAILED": "audit.tower.run.failed",
    "TOWER_RUN_ABANDON": "audit.tower.run.abandon",
    "TOWER_RECORD_UPDATE": "audit.tower.record.update",
    "TOWER_REWARD_GRANT": "audit.tower.reward.grant",
    "TOWER_REWARD_SKIP_DUPLICATE": "audit.tower.reward.skip_duplicate",
    "LAYER4_WARNING_PROGRESS": "audit.layer4_warning.progress",
    "LAYER4_WARNING_RATE_BOOST": "audit.layer4_warning.rate_boost",
    "LAYER4_WARNING_GUARANTEED": "audit.layer4_warning.guaranteed",
    "LAYER4_WARNING_RESET": "audit.layer4_warning.reset",
    "CORE_DROP": "audit.core.drop",
    "PART_EVOLVE": "audit.part.evolve",
    "CORE_PROGRESS": "audit.core.progress",
    "CORE_GUARANTEE": "audit.core.guarantee",
    "PAYMENT_CHECKOUT_CREATE": "audit.payment.checkout.create",
    "PAYMENT_WEBHOOK_RECEIVED": "audit.payment.webhook.received",
    "PAYMENT_COMPLETED": "audit.payment.completed",
    "PAYMENT_GRANT_SUCCESS": "audit.payment.grant.success",
    "PAYMENT_GRANT_SKIP_DUPLICATE": "audit.payment.grant.skip_duplicate",
    "PAYMENT_GRANT_FAILED": "audit.payment.grant.failed",
    "TROPHY_GRANT_SUCCESS": "audit.trophy.grant.success",
    "TROPHY_GRANT_SKIP_DUPLICATE": "audit.trophy.grant.skip_duplicate",
    "TROPHY_GRANT_FAILED": "audit.trophy.grant.failed",
    "EXPLORE_BOOST_GRANT_SUCCESS": "audit.explore_boost.grant.success",
    "EXPLORE_BOOST_GRANT_SKIP_DUPLICATE": "audit.explore_boost.grant.skip_duplicate",
    "EXPLORE_BOOST_GRANT_FAILED": "audit.explore_boost.grant.failed",
    "RESEARCH_BOOST_GRANT": "audit.research_boost.grant",
    "RESEARCH_BOOST_CONSUME": "audit.research_boost.consume",
    "RESEARCH_BOOST_TOGGLE": "audit.research_boost.toggle",
    "LAB_SMALL_BOOST_GRANT": "audit.lab.small_boost.grant",
    "LAB_SMALL_BOOST_USE": "audit.lab.small_boost.use",
    "LAB_TYPING_START": "audit.lab.typing.start",
    "LAB_TYPING_FINISH": "audit.lab.typing.finish",
    "LAB_LEVEL_EXP_GAIN": "audit.lab_level.exp_gain",
    "LAB_LEVEL_LEVEL_UP": "audit.lab_level.level_up",
    "LAB_LEVEL_MILESTONE": "LAB_LEVEL_MILESTONE",
    "INSECT_ROBOT_COMPLETE": "INSECT_ROBOT_COMPLETE",
    "INSECT_RESEARCH_PROGRESS": "INSECT_RESEARCH_PROGRESS",
    "SHARE_CLICK": "audit.share.click",
    "STYLE_SNAPSHOT": "audit.style.snapshot",
    "STYLE_RANK_UP": "audit.style.rank_up",
    "REFERRAL_ATTACH": "audit.referral.attach",
    "REFERRAL_QUALIFIED": "audit.referral.qualified",
    "FACTION_CHOOSE": "audit.faction.choose",
    "FACTION_CHANGE": "audit.faction.change",
    "FACTION_AWARDS_RECALCULATE": "audit.faction.awards.recalculate",
    "FACTION_WEEKLY_BONUS_CLAIM": "audit.faction.weekly_bonus.claim",
    "FACTION_AWARDS_BADGES_GRANT": "audit.faction.awards.badges.grant",
    "FACTION_MISSIONS_CREATE_DEFAULT": "audit.faction.missions.create_default",
    "FACTION_MISSIONS_RECALCULATE": "audit.faction.missions.recalculate",
    "FACTION_MISSIONS_FINALIZE": "audit.faction.missions.finalize",
    "FACTION_GUARDIAN_SET": "audit.faction.guardian.set",
    "FACTION_GUARDIAN_AUTO_PICK": "audit.faction.guardian.auto_pick",
    "FACTION_GUARDIAN_RECALCULATE": "audit.faction.guardian.recalculate",
    "FACTION_GUARDIAN_FINALIZE": "audit.faction.guardian.finalize",
    "FACTION_GUARDIAN_DUEL_GENERATE": "audit.faction.guardian_duel.generate",
    "FACTION_GUARDIAN_DUEL_RUN": "audit.faction.guardian_duel.run",
    "FACTION_STRATEGY_VOTE": "audit.faction.strategy.vote",
    "FACTION_STRATEGY_FINALIZE": "audit.faction.strategy.finalize",
    "FACTION_REPRESENTATIVE_AUTO_PICK": "audit.faction.representative.auto_pick",
    "FACTION_REPRESENTATIVE_SET": "audit.faction.representative.set",
    "FACTION_REPRESENTATIVE_MATCHES_GENERATE": "audit.faction.representative.matches.generate",
    "FACTION_REPRESENTATIVE_MATCHES_RUN": "audit.faction.representative.matches.run",
    "FACTION_REPORT_RECALCULATE": "audit.faction.report.recalculate",
    "FACTION_REPORT_FINALIZE": "audit.faction.report.finalize",
    "SYSTEM_MAINTENANCE_BLOCK": "audit.system.maintenance_block",
    "ADMIN_MAINTENANCE_MODE_SET": "audit.admin.maintenance_mode.set",
    "ADMIN_USER_BAN": "audit.admin.user.ban",
    "ADMIN_USER_UNBAN": "audit.admin.user.unban",
    "ADMIN_USER_PROTECT_LOGIN": "audit.admin.user.protect_login",
    "ADMIN_USER_UNPROTECT_LOGIN": "audit.admin.user.unprotect_login",
    "ADMIN_USER_RENAME": "audit.admin.user.rename",
    "ADMIN_USER_DELETE": "audit.admin.user.delete",
    "ADMIN_ANALYTICS_EXCLUDE": "audit.admin.analytics.exclude",
    "ADMIN_ANALYTICS_INCLUDE": "audit.admin.analytics.include",
    "SECURITY_REGISTRATION_SUSPICIOUS": "audit.security.registration.suspicious",
    "SECURITY_REGISTRATION_RATE_LIMITED": "audit.security.registration.rate_limited",
    "SECURITY_LOGIN_RATE_LIMITED": "audit.security.login.rate_limited",
    "ONBOARDING_HOME_FIRST_VIEW": "audit.onboarding.home.first_view",
    "ONBOARDING_HOME_READY": "audit.onboarding.home_ready",
    "ONBOARDING_FIRST_EXPLORE_CTA_VIEW": "audit.onboarding.first_explore_cta_view",
    "ONBOARDING_FIRST_EXPLORE_CTA_CLICK": "audit.onboarding.first_explore_cta_click",
    "ONBOARDING_LAYER1_FIRST_START": "audit.onboarding.layer1.first_start",
    "ONBOARDING_LAYER1_FIRST_COMPLETE": "audit.onboarding.layer1.first_complete",
    "ONBOARDING_LAYER1_FIRST_WIN": "audit.onboarding.layer1.first_win",
    "BATTLE_RESULT_VIEW": "audit.battle.result.view",
    "EXPLORE_RETRY_CLICK": "audit.explore.retry.click",
    "ONBOARDING_EXPLORE_SECOND_START": "audit.onboarding.explore.second_start",
    "ONBOARDING_EXPLORE_THIRD_START": "audit.onboarding.explore.third_start",
    "ONBOARDING_FIRST_THREE_PROGRESS": "audit.onboarding.first_three_progress",
    "ONBOARDING_FIRST_THREE_COMPLETE": "audit.onboarding.first_three_complete",
    "ONBOARDING_FIRST_THREE_REWARD": "audit.onboarding.first_three_reward",
    "ONBOARDING_FIRST_UPGRADE_SHOWN": "audit.onboarding.first_upgrade.shown",
    "ONBOARDING_FIRST_UPGRADE_CLICK": "audit.onboarding.first_upgrade.click",
    "ONBOARDING_FIRST_UPGRADE_SKIP": "audit.onboarding.first_upgrade.skip",
    "ONBOARDING_FIRST_UPGRADE_COMPLETE": "audit.onboarding.first_upgrade.complete",
    "ONBOARDING_PART_FIRST_DROP": "audit.onboarding.part.first_drop",
    "ONBOARDING_BUILD_FIRST_COMPLETE": "audit.onboarding.build.first_complete",
    "ADMIN_CHAT_DELETE": "audit.admin.chat.delete",
    "ADMIN_RELEASE_TOGGLE": "audit.admin.release.toggle",
    "LAB_SUBMISSION_CREATE": "audit.lab.submission.create",
    "LAB_SUBMISSION_APPROVE": "audit.lab.submission.approve",
    "LAB_SUBMISSION_REJECT": "audit.lab.submission.reject",
    "LAB_SUBMISSION_DISABLE": "audit.lab.submission.disable",
    "LAB_SUBMISSION_LIKE": "audit.lab.submission.like",
    "LAB_SUBMISSION_REPORT": "audit.lab.submission.report",
    "LAB_SUBMISSION_FEATURE": "audit.lab.submission.feature",
    "LAB_SUBMISSION_ADOPTION_CANDIDATE": "audit.lab.submission.adoption_candidate",
    "LAB_SUBMISSION_ADOPTION_UPDATE": "audit.lab.submission.adoption_update",
    "LAB_AI_GENERATE_CLICK": "audit.lab.ai_generate.click",
    "LAB_RACE_ENTRY": "audit.lab.race.entry",
    "LAB_RACE_START": "audit.lab.race.start",
    "LAB_RACE_FINISH": "audit.lab.race.finish",
    "LAB_RACE_RESULT": "audit.lab.race.result",
    "LAB_CASINO_DAILY_GRANT": "audit.lab.casino.daily_grant",
    "LAB_CASINO_BET_PLACE": "audit.lab.casino.bet.place",
    "LAB_CASINO_BET_RESOLVE": "audit.lab.casino.bet.resolve",
    "LAB_CASINO_RACE_START": "audit.lab.casino.race.start",
    "LAB_CASINO_RACE_FINISH": "audit.lab.casino.race.finish",
    "LAB_CASINO_PRIZE_CLAIM": "audit.lab.casino.prize.claim",
    "LAB_MINI_CREATE": "audit.lab.mini.create",
    "LAB_MINI_CARE": "audit.lab.mini.care",
    "LAB_MINI_OBSERVE": "audit.lab.mini.observe",
    "LAB_MINI_RENAME": "audit.lab.mini.rename",
    "LAB_MINI_STATE_CHANGE": "audit.lab.mini.state_change",
    "LAB_MINI_GROWTH": "audit.lab.mini.growth",
    "LAB_MINI_UNLOCK_SPECIES": "audit.lab.mini.unlock_species",
    "MARKET_SELL": "audit.market.sell",
    "MARKET_BUY": "audit.market.buy",
    "MARKET_REFRESH": "audit.market.refresh",
    "MARKET_DAILY_GENERATE": "audit.market.daily_generate",
    "TUTORIAL_LAYER1_STATE_CHANGE": "audit.tutorial.layer1.state_change",
    "TUTORIAL_LAYER1_FORCED_BOSS": "audit.tutorial.layer1.forced_boss",
    "TUTORIAL_LAYER1_BOSS_FAIL_GUIDED": "audit.tutorial.layer1.boss_fail_guided",
    "TUTORIAL_LAYER1_BOSS_HELP_SET": "audit.tutorial.layer1_boss_help.set",
    "TUTORIAL_LAYER1_BOSS_HELP_CONSUME": "audit.tutorial.layer1_boss_help.consume",
    "TUTORIAL_LAYER1_BOSS_BONUS_GRANT": "audit.tutorial.layer1_boss_bonus.grant",
    "NEWBIE_PROTECTION_BOSS_ALERT_GUARANTEED": "audit.newbie_protection.boss_alert_guaranteed",
    "NEWBIE_PROTECTION_BATTLE_ASSIST": "audit.newbie_protection.battle_assist",
    "BOSS_ALERT_PROGRESS": "audit.boss.alert.progress",
    "BOSS_ALERT_READY": "audit.boss.alert.ready",
    "BOSS_ALERT_CONSUME": "audit.boss.alert.consume",
    "LAYER1_FIRST_CLEAR": "audit.layer1.first_clear",
    "LAYER1_FIRST_CLEAR_REWARD": "audit.layer1.first_clear.reward",
    "DAILY_RESEARCH_TASK_CREATE": "audit.daily_research.task.create",
    "DAILY_RESEARCH_TASK_PROGRESS": "audit.daily_research.task.progress",
    "DAILY_RESEARCH_TASK_COMPLETE": "audit.daily_research.task.complete",
    "DAILY_RESEARCH_TASK_CLAIM": "audit.daily_research.task.claim",
    "DAILY_RESEARCH_REWARD_RESERVE": "audit.daily_research.reward.reserve",
    "DAILY_RESEARCH_REWARD_CLAIM": "audit.daily_research.reward.claim",
    "DAILY_RESEARCH_MODAL_VIEW": "audit.daily_research.modal.view",
}

MODULE_STAT_KEYS = ("hp", "atk", "def", "spd", "acc", "cri")
MODULE_STAT_LABELS = {
    "hp": "耐久",
    "atk": "攻撃",
    "def": "防御",
    "spd": "素早さ",
    "acc": "命中",
    "cri": "会心",
}

MODULE_BRAND_DEFINITIONS = {
    "titan": {
        "key": "titan",
        "label": "TITAN HEAVY",
        "short_label": "TITAN",
        "alias_ja": "絶対装甲機関《タイタン》",
        "tagline": "すべての攻撃を受け止め、最後まで立ち続ける。",
        "theme": "重装 / 防衛 / 不沈",
        "description": "機体を巨大な要塞へ変える重装系統。速さを捨て、圧倒的な耐久と防御によって戦線を維持する。",
        "primary_stats": ("hp", "def"),
    },
    "volt": {
        "key": "volt",
        "label": "VOLT EDGE",
        "short_label": "VOLT",
        "alias_ja": "神速演算機関《ヴォルト》",
        "tagline": "敵が動くより先に、勝敗を終わらせる。",
        "theme": "高速 / 先制 / 連撃",
        "description": "演算速度と駆動限界を引き上げる高速系統。一瞬の加速と連続攻撃で敵の行動そのものを許さない。",
        "primary_stats": ("spd", "cri"),
    },
    "eden": {
        "key": "eden",
        "label": "EDEN LOGIC",
        "short_label": "EDEN",
        "alias_ja": "全知解析機関《エデン》",
        "tagline": "未来を読み、存在しないはずの隙を撃ち抜く。",
        "theme": "解析 / 精密 / 必中",
        "description": "敵の挙動を解析し、戦場を数式へ変える精密系統。偶然を排除し、計算された一撃で勝利を確定する。",
        "primary_stats": ("acc", "def"),
    },
    "scrap_x": {
        "key": "scrap_x",
        "label": "SCRAP-X",
        "short_label": "SCRAP-X",
        "alias_ja": "禁断暴走機関《スクラップ・エクス》",
        "tagline": "壊れる寸前こそ、機体は最も美しく燃える。",
        "theme": "暴走 / 背水 / 極限火力",
        "description": "安全装置を破棄し、破損寸前の機体から異常出力を引き出す禁断系統。安定を捨てた者だけが到達できる火力を持つ。",
        "primary_stats": ("atk", "cri"),
    },
    "nova": {
        "key": "nova",
        "label": "NOVA LINK",
        "short_label": "NOVA",
        "alias_ja": "万象接続機関《ノヴァ》",
        "tagline": "すべてを取り込み、戦場そのものへ適応する。",
        "theme": "適応 / 混成 / 万能",
        "description": "異なる演算思想を接続し、戦況に応じて機体構造を変化させる適応系統。固定された弱点を持たない。",
        "primary_stats": MODULE_STAT_KEYS,
    },
}

MODULE_ROLE_DEFINITIONS = {
    "power": {"key": "power", "label": "殲滅演算", "sub_label": "攻撃特化"},
    "guard": {"key": "guard", "label": "絶対防衛", "sub_label": "耐久・防御特化"},
    "speed": {"key": "speed", "label": "神速駆動", "sub_label": "速度特化"},
    "precision": {"key": "precision", "label": "未来照準", "sub_label": "命中特化"},
    "support": {"key": "support", "label": "戦況支配", "sub_label": "補助・適応型"},
    "unstable": {"key": "unstable", "label": "禁忌出力", "sub_label": "暴走・極端型"},
}

MODULE_BRAND_SYNC_RULES = {
    "titan": {"2": {"hp": 4, "def": 4}, "3_add": {"hp": 4, "def": 4, "spd": -2}, "sync_label": "第一装甲解放《アイアン・ウォール》", "sync_label_3": "最終装甲解放《アブソリュート・フォートレス》", "sync_description": "耐久と防御を強化し、機体を前線要塞へ変える。", "sync_description_3": "機動力を犠牲に、崩壊不能の絶対防衛形態へ移行する。"},
    "volt": {"2": {"spd": 4, "cri": 3}, "3_add": {"spd": 4, "cri": 3, "hp": -2}, "sync_label": "第一加速領域《ライトニング・ドライブ》", "sync_label_3": "最終加速領域《ゼロ・フレーム》", "sync_description": "神経伝達と駆動系を同期し、戦場を置き去りにする。", "sync_description_3": "耐久限界を超えて加速し、敵の時間から機体を切り離す。"},
    "eden": {"2": {"acc": 5, "def": 2}, "3_add": {"acc": 5, "def": 2, "cri": -1}, "sync_label": "第一解析領域《オラクル・サイト》", "sync_label_3": "最終解析領域《ラプラス・コード》", "sync_description": "敵の軌道を予測し、攻撃誤差を消去する。", "sync_description_3": "戦場の全情報を演算し、回避という可能性を消滅させる。"},
    "scrap_x": {"2": {"atk": 5, "cri": 3}, "3_add": {"atk": 5, "cri": 3, "def": -3}, "sync_label": "第一禁忌解放《ブラッド・イグニッション》", "sync_label_3": "最終禁忌解放《ラグナロク・オーバー》", "sync_description": "安全制御を解除し、損傷を攻撃出力へ変換する。", "sync_description_3": "機体崩壊を前提に、破滅級の出力を解放する。"},
    "nova": {"2": {"hp": 2, "atk": 2, "def": 2, "spd": 2, "acc": 2, "cri": 2}, "3_add": {"hp": 2, "atk": 2, "def": 2, "spd": 2, "acc": 2, "cri": 2}, "sync_label": "第一適応領域《オール・リンク》", "sync_label_3": "最終適応領域《アカシック・ノヴァ》", "sync_description": "全系統を接続し、機体能力を均等に引き上げる。", "sync_description_3": "あらゆる戦闘思想を統合し、完成された万能機へ進化する。"},
}

MODULE_OS_DEFINITIONS = {
    "TITAN FORTRESS OS": {"name_en": "TITAN FORTRESS OS", "name_ja": "不落絶城型《アブソリュート・タイタン》", "tagline": "倒すことではなく、倒されないことで勝利する。"},
    "VOLT FLASH OS": {"name_en": "VOLT FLASH OS", "name_ja": "神速殲滅型《クロノ・ブレイカー》", "tagline": "敵の一秒を奪い、開戦と同時に決着させる。"},
    "EDEN ANALYZER OS": {"name_en": "EDEN ANALYZER OS", "name_ja": "全知必中型《ラプラス・アイ》", "tagline": "未来を演算し、外れるという結果を排除する。"},
    "SCRAP BERSERK OS": {"name_en": "SCRAP BERSERK OS", "name_ja": "終焉暴走型《ラグナロク・ギア》", "tagline": "機体寿命と引き換えに、限界を超えた破壊を実行する。"},
    "NOVA ADAPTIVE OS": {"name_en": "NOVA ADAPTIVE OS", "name_ja": "万象適応型《アカシック・ノヴァ》", "tagline": "あらゆる敵、あらゆる戦場、あらゆる未来へ適応する。"},
    "HYBRID CONTROL OS": {"name_en": "HYBRID CONTROL OS", "name_ja": "三位複合型《トリニティ・アンノウン》", "tagline": "異なる思想の衝突から、未分類の戦闘理論を生み出す。"},
    "CUSTOM OS": {"name_en": "CUSTOM OS", "name_ja": "未定義構築型《アンノウン・コード》", "tagline": "既存理論に属さない、研究員独自の戦闘構成。"},
    "NO MODULE OS": {"name_en": "NO MODULE OS", "name_ja": "無装演算型《ブランク・コア》", "tagline": "補助演算に頼らず、機体本来の性能だけで戦う。"},
}

MODULE_SYNC_OS_JA_LABELS = {
    "titan": "重装同期型《アイアン・レギオン》",
    "volt": "高速同期型《ライトニング・レイヴ》",
    "eden": "精密同期型《オラクル・システム》",
    "scrap_x": "背水同期型《デッドエンド・ドライブ》",
    "nova": "適応同期型《ユニオン・ノヴァ》",
}
MODULE_OS_JA_LABELS = {key: value["name_ja"] for key, value in MODULE_OS_DEFINITIONS.items()}

MODULE_PROTOCOL_DEFINITIONS = {
    "fortress_guard": {
        "protocol_key": "fortress_guard",
        "brand_key": "titan",
        "required_brand_count": 2,
        "name_ja": "絶対防衛機構《アイギス・ウォール》",
        "quote": "この機体は、落ちない。",
        "short_description": "戦闘開始から3ターン、外部装甲を完全戦闘形態へ移行し、被害を15%軽減する。",
        "battle_start_log": "絶対防衛機構《アイギス・ウォール》――展開。",
        "trigger_log": "多層装甲が衝撃を吸収し、致命傷を拒絶した。",
        "trigger_type": "battle_start",
        "max_activations": 3,
        "is_active": True,
    },
    "emergency_repair": {
        "protocol_key": "emergency_repair",
        "brand_key": "titan",
        "required_brand_count": 3,
        "name_ja": "自己再生機構《リザレクション・ギア》",
        "quote": "まだ、終わるようには設計されていない。",
        "short_description": "機体がHP30%以下へ到達した瞬間、一度だけ予備装甲を再構築して最大HPの12%を回復する。",
        "trigger_log": "自己再生機構《リザレクション・ギア》――緊急起動。",
        "heal_log": "崩壊した装甲が再構築され、機体が戦線へ復帰した。",
        "trigger_type": "hp_threshold",
        "max_activations": 1,
        "is_active": True,
    },
    "opening_acceleration": {
        "protocol_key": "opening_acceleration",
        "brand_key": "volt",
        "required_brand_count": 2,
        "name_ja": "零秒加速《クロノ・アクセル》",
        "quote": "敵が動く頃には、すべて終わっている。",
        "short_description": "開戦直後に演算限界を突破し、最初の2ターンだけ素早さを20%上昇させる。",
        "battle_start_log": "零秒加速《クロノ・アクセル》――時間軸接続。",
        "trigger_log": "機体は知覚限界を超え、敵の時間を追い越した。",
        "trigger_type": "battle_start",
        "max_activations": 2,
        "is_active": True,
    },
    "critical_chain": {
        "protocol_key": "critical_chain",
        "brand_key": "volt",
        "required_brand_count": 3,
        "name_ja": "雷光連鎖《ヴォルト・レゾナンス》",
        "quote": "一撃目は始まりにすぎない。",
        "short_description": "会心の衝撃を次撃へ蓄積し、次の自分の攻撃だけ会心率を+15する。",
        "trigger_log": "雷光連鎖《ヴォルト・レゾナンス》――次撃へ接続。",
        "consume_log": "蓄積された雷光が、次の一撃へ解放された。",
        "trigger_type": "after_critical",
        "max_activations": 2,
        "is_active": True,
    },
    "target_analysis": {
        "protocol_key": "target_analysis",
        "brand_key": "eden",
        "required_brand_count": 2,
        "name_ja": "未来観測《オラクル・トレース》",
        "quote": "その回避は、すでに観測されている。",
        "short_description": "敵の行動軌道を事前演算し、戦闘中の命中判定を+10する。",
        "battle_start_log": "未来観測《オラクル・トレース》――解析開始。",
        "trigger_log": "敵の未来座標が確定し、照準誤差が消去された。",
        "trigger_type": "battle_start",
        "max_activations": 1,
        "is_active": True,
    },
    "miss_correction": {
        "protocol_key": "miss_correction",
        "brand_key": "eden",
        "required_brand_count": 3,
        "name_ja": "因果修正《ラプラス・リライト》",
        "quote": "外れたのではない。修正前だっただけだ。",
        "short_description": "攻撃失敗を演算誤差として再処理し、次の自分の攻撃だけ必中にする。",
        "trigger_log": "因果修正《ラプラス・リライト》――誤差を検出。",
        "consume_log": "演算結果が書き換えられ、次撃の命中が確定した。",
        "trigger_type": "after_miss",
        "max_activations": 2,
        "is_active": True,
    },
    "limit_break": {
        "protocol_key": "limit_break",
        "brand_key": "scrap_x",
        "required_brand_count": 2,
        "name_ja": "崩壊臨界《デッドライン・イグニッション》",
        "quote": "壊れ始めてからが、この機体の本番だ。",
        "short_description": "HP35%以下の間、安全制御を破棄して攻撃を+20%し、防御を-10%する。",
        "on_log": "崩壊臨界《デッドライン・イグニッション》――安全装置解除。",
        "off_log": "耐久回復を確認。崩壊臨界領域から離脱した。",
        "trigger_type": "hp_state",
        "max_activations": 0,
        "is_active": True,
    },
    "unstable_overdrive": {
        "protocol_key": "unstable_overdrive",
        "brand_key": "scrap_x",
        "required_brand_count": 3,
        "name_ja": "禁断過駆動《ラグナロク・バースト》",
        "quote": "生還率は不要。必要なのは、最大出力だけだ。",
        "short_description": "攻撃時20%で制御不能の過剰出力を解放し、与ダメージ1.5倍と最大HP5%の反動を受ける。",
        "trigger_log": "禁断過駆動《ラグナロク・バースト》――臨界突破。",
        "recoil_log": "限界出力の代償として、機体構造が崩壊した。",
        "trigger_type": "before_attack",
        "max_activations": 2,
        "is_active": True,
    },
    "adaptive_shift": {
        "protocol_key": "adaptive_shift",
        "brand_key": "nova",
        "required_brand_count": 2,
        "name_ja": "万象適応《アカシック・シフト》",
        "quote": "未知とは、まだ適応していない既知にすぎない。",
        "short_description": "敵の能力構造を解析し、その戦闘で最も有効な機体形態へ自動変換する。",
        "battle_start_log": "万象適応《アカシック・シフト》――敵性情報を接続。",
        "adapt_logs": {
            "def": "敵火力を解析し、絶対防衛形態へ移行した。",
            "atk": "敵装甲を解析し、対要塞殲滅形態へ移行した。",
            "acc": "敵機動を解析し、未来照準形態へ移行した。",
            "spd": "敵照準を解析し、神速回避形態へ移行した。",
            "hp": "解析不能。全領域耐久形態へ移行した。",
        },
        "trigger_type": "battle_start",
        "max_activations": 1,
        "is_active": True,
    },
    "emergency_reconfiguration": {
        "protocol_key": "emergency_reconfiguration",
        "brand_key": "nova",
        "required_brand_count": 3,
        "name_ja": "戦局再編《ノヴァ・リコンストラクト》",
        "quote": "正解が変わったなら、こちらも変わればいい。",
        "short_description": "4ターン目開始時、戦況を再解析し、現在最も必要な機能へOSを再構築する。",
        "battle_start_log": "戦局再編《ノヴァ・リコンストラクト》――再演算開始。",
        "heal_log": "損傷率を優先し、緊急修復形態へ再構築した。",
        "guaranteed_hit_log": "攻撃誤差を検出し、未来照準形態へ再構築した。",
        "attack_log": "敵耐久低下を確認し、殲滅形態へ再構築した。",
        "defense_log": "戦況維持を優先し、防衛形態へ再構築した。",
        "trigger_type": "turn_start",
        "max_activations": 1,
        "is_active": True,
    },
}

BATTLE_CODE_LIBRARY_DEFAULT_SLOTS = 3

BATTLE_CODE_USAGE_LABELS = {
    "unset": "用途未設定",
    "general": "通常探索",
    "boss": "ボス攻略",
    "speed": "高速周回",
    "stable": "安定重視",
    "comeback": "逆転狙い",
    "experiment": "実験中",
}

BATTLE_CODE_CONDITIONS = {
    "battle_start": {
        "condition_key": "battle_start",
        "name_ja": "開戦宣言《ファースト・オーダー》",
        "short_description": "戦闘開始と同時に、設定した戦闘命令を起動する。",
        "trigger_type": "battle_start",
        "trigger_value": None,
        "max_condition_events": 1,
        "prefix_ja": "先制起動式",
        "prefix_en": "ZERO",
        "timing_label": "戦闘初期化後、1ターン目の行動順計算前",
        "is_active": True,
        "sort_order": 10,
    },
    "low_hp_30": {
        "condition_key": "low_hp_30",
        "name_ja": "崩壊領域《デッドライン》",
        "short_description": "耐久が危険域へ到達したとき、命令を起動する。",
        "trigger_type": "player_hp_threshold",
        "trigger_value": 0.30,
        "max_condition_events": 0,
        "prefix_ja": "終末起動式",
        "prefix_en": "DEADEND",
        "timing_label": "耐久30%以下の状態確認時",
        "is_active": True,
        "sort_order": 20,
    },
    "turn_4_start": {
        "condition_key": "turn_4_start",
        "name_ja": "長期戦移行《フォース・フェイズ》",
        "short_description": "戦闘が長期化した場合、4ターン目に命令を起動する。",
        "trigger_type": "turn_start",
        "trigger_value": 4,
        "max_condition_events": 1,
        "prefix_ja": "長期演算式",
        "prefix_en": "PHASE-4",
        "timing_label": "4ターン目開始時",
        "is_active": True,
        "sort_order": 30,
    },
    "after_miss": {
        "condition_key": "after_miss",
        "name_ja": "誤差検出《エラー・シグナル》",
        "short_description": "攻撃誤差を検出した直後、補正命令を起動する。",
        "trigger_type": "after_player_miss",
        "trigger_value": None,
        "max_condition_events": 0,
        "prefix_ja": "誤差修正式",
        "prefix_en": "REWRITE",
        "timing_label": "自分の攻撃がMISSした直後",
        "is_active": True,
        "sort_order": 40,
    },
    "after_critical": {
        "condition_key": "after_critical",
        "name_ja": "致命共鳴《クリティカル・シグナル》",
        "short_description": "会心出力を検出した直後、次の命令へ接続する。",
        "trigger_type": "after_player_critical",
        "trigger_value": None,
        "max_condition_events": 0,
        "prefix_ja": "臨界連鎖式",
        "prefix_en": "RESONANCE",
        "timing_label": "自分の会心攻撃が成立した直後",
        "is_active": True,
        "sort_order": 50,
    },
    "enemy_low_hp_40": {
        "condition_key": "enemy_low_hp_40",
        "name_ja": "終局判定《フィニッシュ・ライン》",
        "short_description": "敵機の耐久低下を検出し、終局用命令を起動する。",
        "trigger_type": "enemy_hp_threshold",
        "trigger_value": 0.40,
        "max_condition_events": 1,
        "prefix_ja": "終局殲滅式",
        "prefix_en": "EXECUTION",
        "timing_label": "敵HP40%以下へ到達した直後",
        "is_active": True,
        "sort_order": 60,
    },
}

BATTLE_CODE_EFFECTS = {
    "attack_up_15": {
        "effect_key": "attack_up_15",
        "name_ja": "殲滅出力《ブレイク・ドライブ》",
        "short_description": "攻撃演算を強制上昇し、殲滅出力を解放する。",
        "effect_type": "attack_multiplier",
        "value": 0.15,
        "default_max_activations": 0,
        "duration_policy": "condition_dependent",
        "code_name": "BREAK-CODE",
        "affinity_label": "SCRAP-Xと高相性",
        "is_active": True,
        "sort_order": 10,
    },
    "defense_up_15": {
        "effect_key": "defense_up_15",
        "name_ja": "装甲再編《フォートレス・シフト》",
        "short_description": "装甲構造を再編し、敵攻撃への耐性を高める。",
        "effect_type": "defense_multiplier",
        "value": 0.15,
        "default_max_activations": 0,
        "duration_policy": "condition_dependent",
        "code_name": "AEGIS-CODE",
        "affinity_label": "TITANと高相性",
        "is_active": True,
        "sort_order": 20,
    },
    "guaranteed_hit": {
        "effect_key": "guaranteed_hit",
        "name_ja": "因果固定《フェイト・ロック》",
        "short_description": "攻撃軌道を確定し、次撃から回避という結果を排除する。",
        "effect_type": "guaranteed_hit",
        "value": 1,
        "default_max_activations": 2,
        "duration_policy": "next_attack",
        "code_name": "FATE-LOCK",
        "affinity_label": "EDENと高相性",
        "is_active": True,
        "sort_order": 30,
    },
    "heal_8": {
        "effect_key": "heal_8",
        "name_ja": "緊急再生《リカバリー・コア》",
        "short_description": "予備修復資源を投入し、損傷した機体構造を再生する。",
        "effect_type": "heal_percent",
        "value": 0.08,
        "default_max_activations": 1,
        "duration_policy": "instant",
        "code_name": "REBIRTH-CODE",
        "affinity_label": "TITANと高相性",
        "is_active": True,
        "sort_order": 40,
    },
    "speed_up_15": {
        "effect_key": "speed_up_15",
        "name_ja": "神速駆動《クロノ・ドライブ》",
        "short_description": "駆動演算を加速し、行動速度を限界域へ引き上げる。",
        "effect_type": "speed_multiplier",
        "value": 0.15,
        "default_max_activations": 0,
        "duration_policy": "condition_dependent",
        "code_name": "CHRONO-CODE",
        "affinity_label": "VOLTと高相性",
        "is_active": True,
        "sort_order": 50,
    },
    "critical_up_12": {
        "effect_key": "critical_up_12",
        "name_ja": "臨界照準《デス・ポイント》",
        "short_description": "敵機の致命点へ照準を固定し、会心演算率を引き上げる。",
        "effect_type": "critical_bonus",
        "value": 12,
        "default_max_activations": 0,
        "duration_policy": "condition_dependent",
        "code_name": "DEATH-POINT",
        "affinity_label": "EDENと高相性",
        "is_active": True,
        "sort_order": 60,
    },
}
